# Generated by Django 5.0.2 on 2024-03-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_projects_images_projectimages_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
