# Generated by Django 5.0.2 on 2024-03-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_link',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
