# Generated by Django 4.2 on 2024-04-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_experience_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='profile',
        ),
    ]
