# Generated by Django 4.2 on 2024-04-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_experience_profile_remove_projects_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimages',
            name='project',
        ),
        migrations.AddField(
            model_name='projects',
            name='images',
            field=models.ManyToManyField(blank=True, to='core.projectimages'),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(upload_to='project_images'),
        ),
    ]
