# Generated by Django 4.2 on 2024-04-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_framework_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.TextField(),
        ),
    ]
